/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.lab_ed_a_2022_201831504_primera_priactica.View.Menu;

import com.mycompany.lab_ed_a_2022_201831504_primera_priactica.Logic.Client.Bet;
import com.mycompany.lab_ed_a_2022_201831504_primera_priactica.Logic.FileManager.ExportFormatCSV;
import com.mycompany.lab_ed_a_2022_201831504_primera_priactica.Logic.List.ListSimple;
import com.mycompany.lab_ed_a_2022_201831504_primera_priactica.Logic.Results.ResultsBet;
import com.mycompany.lab_ed_a_2022_201831504_primera_priactica.Logic.SortingMethods.SortResults;
import com.mycompany.lab_ed_a_2022_201831504_primera_priactica.Start;
import com.mycompany.lab_ed_a_2022_201831504_primera_priactica.View.Window;
import java.io.IOException;
import java.nio.CharBuffer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Benjamín de Jesús Pérez Aguilar
 */
public class ShowResultTables extends javax.swing.JPanel implements Runnable {

    private Thread hilo = new Thread(this);
    private Window window;
    private final String[] list = {"Nombre", "Listado", "Puntuacion"};
    private DefaultTableModel model;
    private ListSimple<ResultsBet> listResults;

    /**
     * Creates new form ShowResultTables
     */
    public ShowResultTables(Window window) {
        this.window = window;
        initComponents();
        buttonGroup1.add(jRadioButtonName);
        buttonGroup1.add(jRadioButtonP);
        jButtonOrder.setEnabled(false);
        model = new DefaultTableModel(list, 0);
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonMain = new javax.swing.JButton();
        jRadioButtonName = new javax.swing.JRadioButton();
        jRadioButtonP = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonOrder = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButtonMain.setText("Menu Principal");
        jButtonMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainActionPerformed(evt);
            }
        });

        jRadioButtonName.setText("Nombre");

        jRadioButtonP.setText("Puntaje");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Listado", "Punteo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonOrder.setText("Ordenar");
        jButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderActionPerformed(evt);
            }
        });

        jButton1.setText("Export");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMain)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonP)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMain)
                    .addComponent(jRadioButtonName)
                    .addComponent(jRadioButtonP)
                    .addComponent(jButtonOrder)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainActionPerformed
        if (window != null) {
            window.goResults();
            Start.listBet = null;
        }
    }//GEN-LAST:event_jButtonMainActionPerformed

    private void jButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderActionPerformed
        if (!hilo.isAlive()) {
            try {
                jButtonOrder.setEnabled(false);
                hilo = new Thread(this);
                hilo.start();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Aun no a terminado de listar todo, espere forvaro");
        }
    }//GEN-LAST:event_jButtonOrderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setEnabled(false);
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter(".csv", "csv");
        JFileChooser seleccionarArchivo = new JFileChooser();
        seleccionarArchivo.setFileFilter(filtrado);
        if (seleccionarArchivo.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = seleccionarArchivo.getSelectedFile();
            if (!(archivo.canRead() && archivo.getName().endsWith("txt"))) {
                JOptionPane.showMessageDialog(null, "El archivo no es valido");
            } else {
                Thread h = new Thread(new ExportFormatCSV(listResults, archivo,jButton1));
                h.start();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonMain;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JRadioButton jRadioButtonName;
    private javax.swing.JRadioButton jRadioButtonP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Refrescar();
        if (jRadioButtonName.isSelected()) {
            listResults = ((new SortResults()).sortName(listResults));
        } else if (jRadioButtonP.isSelected()) {
            listResults = ((new SortResults()).sortNum(listResults));
        }
        print();
        jButtonOrder.setEnabled(true);
    }

    public void Refrescar() {
        int filas = (model.getRowCount() - 1);
        try {
            for (int i = filas; i >= 0; i--) {// clear table
                Object obj = model.getValueAt(i, 0);
                model.removeRow(i);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void print() {
        if (listResults != null) {//1
            listResults.movenStart();//1
            boolean begin = (listResults != null) && listResults.getSpotter() != null;//2
            while (begin) {            //n
                begin = !(listResults.getSpotter().getNext() == null);//n
                ResultsBet result = (ResultsBet) listResults.getSpotter().getObject(); //n
                Object[] list = {result.getBet().getPeople().getName(), result.getBet().getAmount(), result.getFinalPunctuation()};//3
                model.addRow(list);//1
                /*debe de pintar aqui*/
                listResults.movenNext();
            }
        }
    }

    public void setListResults(ListSimple<ResultsBet> listResults) {
        this.listResults = listResults;
    }

    public Thread getHilo() {
        return hilo;
    }

}
